/* -------------------------------------------------------------------------- */
/* process_util.h                                                             */
/* -------------------------------------------------------------------------- */
void setPFC01Pid(int pid);
void setPFC02Pid(int pid);
void setPFC03Pid(int pid);
void setReaderPid(int pid);
void setTransPid(int pid);
void setFailGenPid(int pid);
void getPFC01Pid(char *sPid);
void getPFC02Pid(char *sPid);
void getPFC03Pid(char *sPid);
void getReaderPid(char *sPid);
void getTransPid(char *sPid);
void getFailGenPid(char *sPid);
